schema {
  query: Query
  mutation: Mutation
}

type Query {
  # セットリスト一覧
  setList(userId: String!): [Set]!
  # 学習セット
  studySet(setId: String!): [Word]!
  # 学習履歴
  studyHistory(userId: String!, setId: String!): [Word]!
  # テキストから音声に変更する
  studyPolly(text: String!): Speech
}

type Mutation {
  # セット作成
  setCreate(userId: String!, name: String!): Set
  # セット削除
  setDelete(userId: String!, setId: String!): Set
  # 画像から単語読み取り
  image2Word(bucketKey: String!): Newwords!
  # 単語新規登録
  registWords(input: RegistWordsInput!): [Word]
  # 単語検定を保存する
  studySave(input: StudySaveInput!): Boolean
}

input RegistWordsInput {
  setID: String!
  words: [String]!
}

input StudyRecord {
  word: String!
  correct: Boolean
  times: Int!
}

input StudySaveInput {
  setID: String!
  words: [StudyRecord]!
}

type Newwords {
  # 新規単語
  words: [String]
}

type Set {
  # userId
  userId: ID!
  # setId
  setId: ID!
  # セット名
  name: String
}

type Speech {
  # Content-Type
  contentType: String!
  # 音声URL
  url: String!
}

type User {
  # userId
  userId: ID!
  # user名
  username: String
}

type Word {
  # セットID
  setId: ID!
  # 単語
  word: String!
  # 発音
  pronunciation: String
  # 語彙
  vocabulary: String
  # 学習時間
  studyDate: String
  # 次回学習時間
  nextDate: String!
  # 学習回数
  times: Int!
}
