AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Default: dev
    Type: String
Resources:
  AddNewWords:
    DeletionPolicy: Retain
    Properties:
      CodeUri: s3://deployment-projects/d15ab3d5e672d85caf53bf4ae75f5b6e
      Environment:
        Variables:
          TABLE_PRONUNCIATION: Pronunciation
          TABLE_WORD: Word
      Events:
        AddNewWordsApi:
          Properties:
            Method: get
            Path: /test/aaa
            RestApiId: 9karytns8f
          Type: Api
      FunctionName: AddNewWords
      Handler: appsync/add-new-words/index.handler
      MemorySize: 256
      Runtime: nodejs8.10
      Timeout: 5
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
