AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
Parameters:
  Project:
    Type: String
    Default: PocketCards

Resources:
  AddNewWords:
    Type: AWS::Serverless::Function
    DeletionPolicy: Retain
    Properties:
      Handler: appsync/add-new-words/index.handler
      Runtime: nodejs8.10
      FunctionName: AddNewWords
      MemorySize: 256
      Timeout: 5
      CodeUri: ../../../../dist/dev
      Environment:
        Variables:
          TABLE_WORD: !Sub ${env}-${Project}-Word
          TABLE_PRONUNCIATION: !Sub ${env}-${Project}-Pronunciation
      Events:
        AddNewWordsApi:
          Type: Api
          Properties:
            Path: /test/aaa
            Method: get
            # RestApiId: !ImportValue 9karytns8f