query StudySet {
  studySet(userId: "wwalpha", setId: "7efce5ed-f65f-42b0-9229-6feedb5f4ee0") {
    # セットID
    setId
    # 単語
    word
    # 発音
    pronounce
    # 語彙
    vocabulary
    # 学習時間
    studyDate
    # 次回学習時間
    nextDate
    # 学習回数
    times
  }
}
