schema {
  query: Query
  mutation: Mutation
}

type Query {
  # ユーザ情報
  user: User
  # 操作ステータス
  status: Status
  # 画面情報
  screen: Screen
  # 新規登録単語
  newwords: Newwords
}

type Mutation {
  # ユーザ情報を更新する
  updateUser(id: String!, username: String!): User
  # 画面パスを更新する
  updatePath(path: Int!): Screen
}

input UserInput {
  id: ID!
  username: String
}

# input RegistWordInput {
#   words: [String]!
# }

type Newwords {
  words: [String]
}

type User {
  id: ID!
  username: String
}

type Screen {
  path: Int!
}

type Status {
  setId: String
}
