schema {
  query: Query
  mutation: Mutation
}

type Query {
  user: User
  app: App
}

type Mutation {
  updateUser(id: String!, username: String!): User
  updatePath(path: Int): App
}

input UserInput {
  id: ID!
  username: String!
}

type User {
  id: ID!
  username: String!
}

type App {
  screen: String!
}
