type User {
  id: ID!
  username: String!
}

type App {
  id: ID!
}

type Newwords {
  words: [String]
}

type User {
  id: ID!
  username: String
}

type Screen {
  path: Int!
}

type Status {
  setId: String
}