input RegistWordsInput {
  setId: String!
  words: [String]!
}

input StudyAnswerInput {
  setId: ID!
  word: String!
  correct: Boolean!
  times: Int!
}

type Mutation {
  # 画像から単語読み取り
  image2Word(bucketKey: String!): ImageWord!

  # 単語新規登録
  registWords(input: RegistWordsInput!): [Word]

  # 単語検定を保存する
  studyAnswer(input: StudyAnswerInput!): Boolean
}

type Query {
  # 学習セット
  studySet(setId: String!): [Word]!

  # 学習履歴
  studyHistory(userId: String!, setId: String!): [Word]!

  # テキストから音声に変更する
  studyPolly(text: String!): Speech
}

