type Query {
  # セットリスト一覧
  setList(userId: String!): [Set]!
}

type Mutation {
  # セット作成
  setCreate(userId: String!, name: String!): Set

  # セット削除
  setDelete(userId: String!, setId: String!): Set
}