AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: dev
  Project:
    Type: String
    Default: PocketCards

Resources:
  StudySave:
    Type: AWS::Serverless::Function
    DeletionPolicy: Retain
    Properties:
      Handler: appsync/study-save/index.handler
      Runtime: nodejs8.10
      FunctionName: !Sub ${env}-${Project}-StudySave
      MemorySize: 256
      Timeout: 5
      CodeUri: ../../../../dist/dev
      Environment:
        Variables:
          TABLE_WORD: !Sub ${env}-${Project}-Word
          TABLE_TIMES: !Sub ${env}-${Project}-Times
          TZ: Asia/Tokyo