# input UserInput {
#   id: ID!
#   username: String
# }

# input WordInput {
#   word: String!
#   pronunciation: String
#   vocabulary: String
#   times: Int!
# }

extend type Mutation {
  # ユーザ情報を更新する
  updateUser(id: String!, username: String!): User!
  # 画面パスを更新する
  updatePath(path: Int!): Status!
    # 画面パスを更新する
  updateSetId(id: String!): Status!

  # # ローカルの新規単語リストをクリアする
  # clearNewwords: Newwords
  # # ローカルの単語リストから単語を削除する
  # removeWord(word: String!): Newwords

  # 学習リストをローカルに保存する
  # saveWordList(list: [WordInput!]!): Boolean
  # 学習リストをローカルに保存する
  clearWordList: Boolean
  # 前のカード情報
  prevCard: Card
  # 次のカード情報
  nextCard: Card
}