input UserInput {
  id: ID!
  username: String!
}

input RegistWordInput {
  words: [String]
}

type Mutation {
  updateUser(id: String!, username: String!): User
  updatePath(path: Int!): App
  registWords(words: RegistWordInput!): Newwords
}