# input UserInput {
#   id: ID!
#   username: String
# }

# input WordInput {
#   word: String!
#   pronunciation: String
#   vocabulary: String
#   times: Int!
# }

extend type Mutation {
  # ユーザ情報を更新する
  updateUser(id: String!, username: String!): User!
  # 画面パスを更新する
  updatePath(path: Int!): Status!
    # 画面パスを更新する
  updateSetId(id: String!): Status!

  # ローカルの新規単語リストをクリアする
  clearNewwords: Boolean
  # ローカルの単語リストから単語を削除する
  removeNewword(word: String!): Boolean
}