# 新規単語管理
# type Newwords {
#   words: [String]
# }

# ユーザ情報
type User {
  id: ID!
  username: String
}

# アプリステータス
type Status {
  setId: String
  path: Int!
  cardIndex: Int!
}

# 単語情報
# type Word {
#   word: String!
#   pronunciation: String
#   vocabulary: String
#   times: Int!
# }

# カード情報
type Card {
  word: String!
  pronunciation: String
  vocabulary: String
  times: Int!
}
