# 新規単語管理
type Newwords {
  words: [String!]!
}

# ユーザ情報
type User {
  id: ID!
  username: String
}

# 画面パス
type Screen {
  path: Int!
}

# アプリステータス
type Status {
  setId: String
}

# 単語情報
type Word {
  word: String!
  pronunciation: String
  vocabulary: String
  times: Int!
}

# カード情報
type Card {
  word: String!
  pronunciation: String
  vocabulary: String
  times: Int!
}

# 学習情報
type Study {
  list: [Word]!
  index: Int!
  card: Card
}