

type App {
  screen: Screen
  user: User
  status: Status
}

type Newwords {
  words: [String]
}

type User {
  id: ID!
  username: String
}

type Screen {
  path: Int!
}

type Status {
  setId: String
}