type Mutation {
  addMessage(
    bucket: String!,
    key: String!,
    region: String!,
    mimeType: String!
  ): RaspberryPi
  addTextMessage(message: String!): RaspberryPi
}

type Query {
  listMessage: S3Object
}

type RaspberryPi {
  signedURL: String
  message: String
}

type S3Object {
  bucket: String!
  key: String!
  region: String!
}

input S3ObjectInput {
  bucket: String!
  key: String!
  region: String!
  localUri: String!
  mimeType: String!
}

type Subscription {
  subscribeToRecvMessage: RaspberryPi
    @aws_subscribe(mutations: ["addMessage","addTextMessage"])
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}