schema {
  query: Query
  mutation: Mutation
}

type Query {
  user: User
}

type Mutation {
  updateUser(user: UserInput!): User
}

input UserInput {
  id: ID!
  username: String!
}

type User {
  id: ID!
  username: String!
}
