schema {
  query: Query
  mutation: Mutation
}

type Query {
  user: User
  app: App
}

type Mutation {
  updateUser(id: String!, username: String!): User
  updatePath(path: Int!): App
  registWords(words: RegistWordInput!): Newwords
}

input UserInput {
  id: ID!
  username: String!
}

input RegistWordInput {
  words: [String]
}

type User {
  id: ID!
  username: String!
}

type App {
  path: String!
}

type Newwords {
  words: [String]
}
