schema {
  query: Query
}

type Newwords {
  words: [String]!
}

type User {
  id: ID!
  username: String
}

type Status {
  setId: String
  path: Int!
  cardIndex: Int!
}

extend type Mutation {
  updateUser(id: String!, username: String!): User!
  updatePath(path: Int!): Status!
  updateSetId(id: String!): Status!
  clearNewwords: Boolean
  removeNewword(word: String!): Boolean
}

extend type Query {
  user: User!
  status: Status!
  newwords: Newwords!
}
