
type Mutation {
  # セット作成
  createSet(userId: ID!, name: String!): Set

  # セット削除
  deleteSet(setId: ID!): Set

  # 画像から単語読み取り
  wordWithImage(bucketKey: String!): [String]

  # 単語新規登録
  addNewWords(setId: String!, words: [String]!): [Word]
}

schema {
	query: Query
	mutation: Mutation
	# subscription: Subscription
}