projects:
  dev-PocketCards:
    schemaPath: graphql\appsync\schema.json
    includes:
      - src\graphql\appsync\mutations.ts
      - src\graphql\appsync\queries.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: jw4s4q3gqbgkpbhr2pnk5uziji
        codeGenTarget: typescript
        docsFilePath: src\graphql\appsync
        region: ap-northeast-1
      endpoints:
        prod: >-
          https://wimdgmn6p5fq7kw7bp5w24xeu4.appsync-api.ap-northeast-1.amazonaws.com/graphql
