projects:
  dev-PocketCards:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\mutations.ts
      - src\graphql\**\queries.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: jw4s4q3gqbgkpbhr2pnk5uziji
        codeGenTarget: typescript
        # generatedFileName: src\graphql\types.ts
        docsFilePath: src\graphql
        region: ap-northeast-1
      endpoints:
        prod: >-
          https://wimdgmn6p5fq7kw7bp5w24xeu4.appsync-api.ap-northeast-1.amazonaws.com/graphql
