// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  // 'aws_cognito_identity_pool_id': 'ap-northeast-1:a1e28e02-d12a-4c5e-9d80-893d7c23b286',
  // 'aws_cognito_region': 'ap-northeast-1',
  // 'aws_user_pools': 'enable',
  // 'aws_user_pools_id': 'ap-northeast-1_JzZThk6Q8',
  // 'aws_user_pools_web_client_id': 'njegb0thfm3b21oqoadtp0k0f',
  'aws_appsync_graphqlEndpoint': 'https://wimdgmn6p5fq7kw7bp5w24xeu4.appsync-api.ap-northeast-1.amazonaws.com/graphql',
  'aws_appsync_region': 'ap-northeast-1',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
  // Storage: {
  //   bucket: 'dev-pocketcards',
  //   identityPoolId: 'ap-northeast-1:a1e28e02-d12a-4c5e-9d80-893d7c23b286',
  // }

  Auth: {
    identityPoolId: 'ap-northeast-1:9283af32-252b-479c-a39d-1a13e59c17bb', //REQUIRED - Amazon Cognito Identity Pool ID
    region: 'ap-northeast-1', // REQUIRED - Amazon Cognito Region
    userPoolId: 'ap-northeast-1_JzZThk6Q8', //OPTIONAL - Amazon Cognito User Pool ID
    userPoolWebClientId: 'njegb0thfm3b21oqoadtp0k0f', //OPTIONAL - Amazon Cognito Web Client ID
  },
  Storage: {
    bucket: 'dev-pocketcards', //REQUIRED -  Amazon S3 bucket
    region: 'ap-northeast-1', //OPTIONAL -  Amazon service region
  }
}

export default awsmobile;
