
type Query {
  # セットリスト一覧
  sets(userId: ID!): [Set]

  # 単語一覧
  words(setId: ID!): [Word]
}

type Mutation {
  # セット作成
  createSet(userId: ID!, name: String!): Set

  # セット削除
  deleteSet(setId: ID!): Set
}

schema {
	query: Query
	mutation: Mutation
	# subscription: Subscription
}